require("modules.input.keybinds.applications")
require("modules.input.keybinds.actions")
require("modules.input.keybinds.hardware")
require("modules.input.keybinds.workspaces")
require("modules.input.keybinds.windows")
