[menu]
title = "Utility Selector"

[[item]]
label = "Emoticon"
icon  = ""
exec  = "bash $HOME/.config/rofi/modules/emoji-selector/main.sh"

[[item]]
label = "Screenshot"
icon  = "󰹑"
exec  = "bash $HOME/.config/rofi/modules/screenshot-picker/main.sh"

[[item]]
label = "Clipboard Manager"
icon  = ""
exec  = "bash $HOME/.config/rofi/modules/clipboard-manager/main.sh"

[[item]]
label = "Hyprpicker"
icon  = ""
exec  = "bash $HOME/.config/rofi/modules/colors-picker/main.sh"
