# CURRENT SONG
label {
    monitor =
    text = cmd[update:1000] echo "$(~/.config/hypr/scripts/media/song-metadata.sh)"
    color = $foreground
    font_size = 15
    font_family = SF Pro Display Bold
    position = 0, 60
    halign = center
    valign = bottom
}
