# ---- Reboot ----------------------------
label {
    monitor =
    text = 󰜉
    color = $foreground
    font_size = 18
    onclick = reboot now
    position = 210, 45
    halign = center
    valign = bottom
}

# ---- Power off ----------------------------
label {
    monitor =
    text = 󰐥
    color = $foreground
    font_size = 18
    onclick = shutdown now
    position = 1030, 45
    halign = left
    valign = bottom
}

# ---- Suspend ----------------------------
label {
    monitor =
    text = 󰤄
    color = $foreground
    font_size = 18
    onclick = systemctl suspend
    position = -1030, 45
    halign = right
    valign = bottom
}
