# ---- Colorscheme ---------------------------------
source = ~/.cache/wal/colors-hyprland.conf

# ---- Components ---------------------------------
source = lockscreen/environment.conf
source = lockscreen/appearance.conf
source = lockscreen/authentication.conf
source = lockscreen/media-player.conf
source = lockscreen/timekeeping.conf

# source = lockscreen/powerctrl.conf
