[General]
# ──── Configuration ───────────────────────────
autoColor=true
use24HourClock=false

# ──── Fallback colors ───────────────────────────
primaryColor=#E3E3DC
accentColor=#A9C78F
backgroundColor=#1A1C18
textColor=#E3E3DC

# ──── Typography ───────────────────────────
fontFamily=FlexRounded
fontSize=12
